name: Build binaries

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2

      - name: Fix apt sources
        run: |
          apt-get update
          apt-get -y install dirmngr
          echo 'deb http://us.archive.ubuntu.com/ubuntu/ bionic main' >> /etc/apt/sources.list
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          apt-get update
      - name: Install and update packages
        run: |
          apt-get -y install python3 python3-pip p7zip-full libarchive13
          python3 --version
          python3 -m pip install --upgrade pip setuptools

      - name: Compile tests
        run: |
          make -C tests/software-keyboard
          make -C tests/mii-selector

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: Source & Binaries
          path: tests
        
